# Generated by Django 3.1.1 on 2021-09-28 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLineItemDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Required_on_date', models.DateTimeField(auto_now_add=True)),
                ('Quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Rate_per_unit', models.IntegerField()),
                ('Unit', models.CharField(choices=[('KG', 'KG'), ('METRE', 'METRE')], max_length=30)),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.articlemaster')),
                ('Colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.colormaster')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Transaction_Number', models.IntegerField(unique=True)),
                ('Transaction_Status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('CLOSE', 'CLOSE')], max_length=20)),
                ('Remarks', models.CharField(max_length=20, null=True)),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.branchmaster')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.companyledgermaster')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.departmentmaster')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Gross_Quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Net_Quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Unit', models.CharField(choices=[('KG', 'KG'), ('METRE', 'METRE')], max_length=30)),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.articlemaster')),
                ('Colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.colormaster')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.companyledgermaster')),
            ],
        ),
    ]
